gloryhall/Controllers/MatchController.cs
using System;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using gloryhall.Data.Models;
using gloryhall.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;

namespace gloryhall.Controllers

{
    public class MatchController : Controller
    {
        private AppDBContent db;
        IWebHostEnvironment _appEnvironment;
        UserManager<User> _userManager;
        public MatchController(AppDBContent context, IWebHostEnvironment appEnvironment, UserManager<User> userManager)
        {
            db = context;
            _appEnvironment = appEnvironment;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id)
        {
            //var match = db.Match.Where(p => p.id == id).ToArray();
            //Thread thread = new Thread();
            //thread.name = "Test";
            //thread.match = match[0];
            //db.Thread.Add(thread);
            //await db.SaveChangesAsync();
            ViewData["id"] = id;
            return View(await db.Thread.Include(p=>p.match).Where(p => p.match.id == id).ToListAsync());
        }

        public async Task<IActionResult> Edit(int id)
        {
            Match match = await db.Match.FindAsync(id);
            if (match == null)
            {
                return NotFound();
            }
            else
            {
                EditMatchViewModel model = new EditMatchViewModel { id = id, name = match.name, team1 = match.team1, team2 = match.team2, scoresTeam1 = match.scoresTeam1, scoresTeam2 = match.scoresTeam2 };
                return View(model);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditMatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                Match match = await db.Match.FindAsync(model.id);
                if (match != null)
                {
                    match.name = model.name;
                    match.team1 = model.team1;
                    match.team2 = model.team2;
                    match.scoresTeam1 = Convert.ToSByte(model.scoresTeam1);
                    match.scoresTeam2 = Convert.ToSByte(model.scoresTeam2);

                    await db.SaveChangesAsync();
                    
                    return RedirectToAction("Index", "Home");   
                }
            }
            return View(model);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create(CreateMatchViewModel model)
        {
            if (ModelState.IsValid)
            {
                Match match = new Match();
                match.name = model.name;
                match.team1 = model.team1;
                match.team2 = model.team2;
                match.scoresTeam1 = Convert.ToSByte(model.scoresTeam1);
                match.scoresTeam2 = Convert.ToSByte(model.scoresTeam2);
                match.img = model.img.FileName;
                // путь к папке Files
                string path = "/img/" + model.img.FileName;
                // сохраняем файл в папку Files в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + path, FileMode.Create))
                {
                    await model.img.CopyToAsync(fileStream);
                }
                db.Match.Add(match);
                await db.SaveChangesAsync();
                
                return RedirectToAction("Index", "Home");
                
            }
            return View(model);
        }

        public IActionResult CreateThread(int id){
            CreateThreadViewModel model = new CreateThreadViewModel { id = id };
            return View(model);
        }
        

        [HttpPost]
        public async Task<IActionResult> CreateThread(CreateThreadViewModel model)
        {
            if (ModelState.IsValid)
            {
                Thread thread = new Thread();
                Match match = db.Match.Find(model.id);
                thread.match = match;
                thread.name = model.name;
                thread.user = await _userManager.GetUserAsync(User);
                
                db.Thread.Add(thread);
                await db.SaveChangesAsync();

                return RedirectToAction("Index", "Match", new { id = model.id });

            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> DeleteThread(string id)
        {
            Thread thread = await db.Thread.Include(p=>p.match).FirstOrDefaultAsync(i => i.id == Convert.ToInt32(id));
            var messages = await db.Messages.Include(p => p.Thread).Where(p => p.Thread.id == Convert.ToInt32(id)).ToListAsync();
            if (messages != null)
            {
                db.Messages.RemoveRange(messages);
                await db.SaveChangesAsync();
            }
            if (thread != null)
            {
                db.Thread.Remove(thread);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Match", new { id = thread.match.id });
        }

        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            Match match = await db.Match.FindAsync(Convert.ToInt32(id));
            
            if (match != null)
            {
                db.Match.Remove(match);
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

gloryhall/Controllers/MessagesController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using gloryhall.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace gloryhall.Controllers
{
    [Authorize]
    public class MessagesController : Controller
    {
        private AppDBContent db;
        IWebHostEnvironment _appEnvironment;
        UserManager<User> _userManager;

        public MessagesController(AppDBContent context, IWebHostEnvironment appEnvironment, UserManager<User> userManager)
        {
            db = context;
            _appEnvironment = appEnvironment;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(int id){
            ViewData["id"] = id;
            var temp = await db.Messages.Include(p => p.Thread).Include(p=>p.User).Where(p => p.Thread.id == id).OrderBy(p => p.date).ToListAsync();
            return View(temp);
        }

    }
}

gloryhall/Views/Match/Create.cshtml
@model gloryhall.Data.ViewModels.CreateMatchViewModel
@{
    ViewBag.Title = "Добавление турнира";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form asp-action="Create" asp-controller="Match" enctype="multipart/form-data">
    
    <div class="form-group">
        <label asp-for="name" class="control-label">Название</label>
        <input type="text" asp-for="name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="team1" class="control-label">Команда1</label>
        <input type="text" asp-for="team1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="team2" class="control-label">Команда2</label>
        <input type="text" asp-for="team2" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="scoresTeam1" class="control-label">очки Команды1</label>
        <input type="number" asp-for="scoresTeam1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="scoresTeam2" class="control-label">очки Команды2</label>
        <input type="number" asp-for="scoresTeam2" class="form-control" />
    </div>
    <div class="form-group">
        <input type="file"  asp-for="img" class="file-select" accept="image/*"/>
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

gloryhall/Views/Match/CreateThread.cshtml
@model gloryhall.Data.ViewModels.CreateThreadViewModel
@{
    ViewBag.Title = "Добавление треда";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form asp-action="CreateThread" asp-controller="Match" enctype="multipart/form-data">

    <div class="form-group">
        <label asp-for="name" class="control-label">Название</label>
        <input type="text" asp-for="name" class="form-control" />
        <input type="hidden" asp-for="id" value="@Model.id" />
    </div>
    
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

gloryhall/Views/Match/Edit.cshtml
@model gloryhall.Data.ViewModels.EditMatchViewModel
@{
    ViewBag.Title = "Редактирование турнира";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<form asp-action="Edit" asp-controller="Match">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input type="hidden" asp-for="id" />
    </div>
    <div class="form-group">
        <label asp-for="name" class="control-label">Название</label>
        <input type="text" asp-for="name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="team1" class="control-label">Команда1</label>
        <input type="text" asp-for="team1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="team2" class="control-label">Команда2</label>
        <input type="text" asp-for="team2" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="scoresTeam1" class="control-label">очки Команды1</label>
        <input type="number" asp-for="scoresTeam1" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="scoresTeam2" class="control-label">очки Команды2</label>
        <input type="number" asp-for="scoresTeam2" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
    </div>
</form>

gloryhall/Views/Match/Index.cshtml
@model IEnumerable<gloryhall.Data.Models.Thread>
@{
    ViewBag.Title = "Все чаты";
}
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            <li><a href="#" class="text-white">Follow on Twitter</a></li>
                            <li><a href="#" class="text-white">Like on Facebook</a></li>
                            <li><a href="#" class="text-white">Email me</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar navbar-dark bg-dark shadow-sm">
            <div class="container d-flex justify-content-between">
                @if (User.Identity.IsAuthenticated)
                {
                    <a href="#" class="navbar-brand d-flex align-items-center">

                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-controller" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M11.119 2.693c.904.19 1.75.495 2.235.98.407.408.779 1.05 1.094 1.772.32.733.599 1.591.805 2.466.206.875.34 1.78.364 2.606.024.815-.059 1.602-.328 2.21a1.42 1.42 0 0 1-1.445.83c-.636-.067-1.115-.394-1.513-.773a11.307 11.307 0 0 1-.739-.809c-.126-.147-.25-.291-.368-.422-.728-.804-1.597-1.527-3.224-1.527-1.627 0-2.496.723-3.224 1.527-.119.131-.242.275-.368.422-.243.283-.494.576-.739.81-.398.378-.877.705-1.513.772a1.42 1.42 0 0 1-1.445-.83c-.27-.608-.352-1.395-.329-2.21.024-.826.16-1.73.365-2.606.206-.875.486-1.733.805-2.466.315-.722.687-1.364 1.094-1.772.486-.485 1.331-.79 2.235-.98.932-.196 2.03-.292 3.119-.292 1.089 0 2.187.096 3.119.292zm-6.032.979c-.877.185-1.469.443-1.733.708-.276.276-.587.783-.885 1.465a13.748 13.748 0 0 0-.748 2.295 12.351 12.351 0 0 0-.339 2.406c-.022.755.062 1.368.243 1.776a.42.42 0 0 0 .426.24c.327-.034.61-.199.929-.502.212-.202.4-.423.615-.674.133-.156.276-.323.44-.505C4.861 9.97 5.978 9.026 8 9.026s3.139.943 3.965 1.855c.164.182.307.35.44.505.214.25.403.472.615.674.318.303.601.468.929.503a.42.42 0 0 0 .426-.241c.18-.408.265-1.02.243-1.776a12.354 12.354 0 0 0-.339-2.406 13.753 13.753 0 0 0-.748-2.295c-.298-.682-.61-1.19-.885-1.465-.264-.265-.856-.523-1.733-.708-.85-.179-1.877-.27-2.913-.27-1.036 0-2.063.091-2.913.27z" />
                            <path d="M11.5 6.026a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1 1a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm2 0a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-1 1a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0zm-7-2.5h1v3h-1v-3z" />
                            <path d="M3.5 6.526h3v1h-3v-1zM3.051 3.26a.5.5 0 0 1 .354-.613l1.932-.518a.5.5 0 0 1 .258.966l-1.932.518a.5.5 0 0 1-.612-.354zm9.976 0a.5.5 0 0 0-.353-.613l-1.932-.518a.5.5 0 1 0-.259.966l1.932.518a.5.5 0 0 0 .612-.354z" />
                        </svg>
                        <strong>@User.Identity.Name</strong>
                        <form method="post" asp-controller="Account" asp-action="Logout">
                            <input type="submit" value="Logout" class="navbar-toggler" data-toggle="collapse" />
                        </form>
                    </a>
                }
                else
                {
                    <a href="@Url.Action("Login", "Account")" class="navbar-brand d-flex align-items-center">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-emoji-frown" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z" />
                            <path fill-rule="evenodd" d="M4.285 12.433a.5.5 0 0 0 .683-.183A3.498 3.498 0 0 1 8 10.5c1.295 0 2.426.703 3.032 1.75a.5.5 0 0 0 .866-.5A4.498 4.498 0 0 0 8 9.5a4.5 4.5 0 0 0-3.898 2.25.5.5 0 0 0 .183.683z" />
                            <path d="M7 6.5C7 7.328 6.552 8 6 8s-1-.672-1-1.5S5.448 5 6 5s1 .672 1 1.5zm4 0c0 .828-.448 1.5-1 1.5s-1-.672-1-1.5S9.448 5 10 5s1 .672 1 1.5z" />
                        </svg>
                        <strong>Log In</strong>
                    </a>
                }
            </div>
        </div>
    </header>

    <a href="@Url.Action("CreateThread", "Match")?id=@ViewData["id"]"> Добавить тред</a>

    <div class="container">
        @{ foreach (var item in Model)
            {
                <div class="card-deck mb-3 text-center">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-header">
                            <h4 class="my-0 font-weight-normal">@item.name</h4>
                        </div>
                        <div class="card-body">
                            <ul class="list-unstyled mt-3 mb-4">
                                <li>@item.match.team1</li>
                                <li>@item.match.team2</li>
                            </ul>
                            <button type="button" class="btn btn-lg btn-block btn-outline-primary"><a href="@Url.Action("Index", "Messages")?id=@item.id"> Start flooding </a></button>
                            @if (User.IsInRole("moderator") || User.IsInRole("admin"))
                            {
                                <form asp-action="DeleteThread" asp-route-id="@item.id" method="post">
                                    <input type="submit" value="Delete" class="btn btn-sm btn-outline-secondary" data-toggle="collapse" />
                                </form>
                            }
                        </div>
                    </div>
                </div>
            }
        }
    </div>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>window.jQuery || document.write('<script src="/docs/4.5/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="/docs/4.5/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>